language: node_js
node_js:
- '6'
- '7'
branches:
  only:
  - master
  - develop
  - /^v?(\d\.){2}\d$/
  - /^greenkeeper/.*$/
notifications:
  email:
  - nfantone@gmail.com
cache:
  bundler: true
  directories:
  - node_modules
script: npm run validate && npm run coverage
deploy:
  provider: npm
  email: nfantone@gmail.com
  api_key:
    secure: fW4rytvfGHwH+sVwby/AkyyjXFiBOYalSPQHBFB6HMFgHV2x9xtD7MKtsNRkobYjnK0mwU3zcwek9DsCs4/YNUFAUs4x1GkHaDn4Zr+AfY1pHlb85C+w+PIkr2SdhQg9gq2dtnZ35YPkAbmsLw9SXMh7xIUOa2H9jSze0iHx8K9u2M1Ph2DucRfoRC1d0MJUTl1qDLTrRi3cXC4+4CdBv/IwBa35WeFG/L/yHzaN3rAEQBlDZ8Nu+Htl3+/X7gTBkcEFh7s3oIyAGL+qENZmp4ven2muAhOZWdgNvwIPhFTbt1W4RZBHlIToo8h5DXXwx/h4wvWMujVGlVOUgLpHFf8HamYm12kXBZONOBFPHZySO1ETXYYnOc4n1RqdMYj1UPgOXimX0TK5qnBa/bdEg05dBLgu4vQw2uVJtOY/TOVwt25ZnMsEuho0osVQca+4xAaODPKWfGC0/mKO5axHqTTqoZHX/YEzf3QKZgHomdzGPUxlbK29tw9Plt3Oo6RmIVMP7GbxZOSE+RE1ySqKULN9cusbYW6Xc+f+qCeeC2vOOEqLOPe/P+BSFE/x9/1R3Zrjci8L9VlaW7n1VCakTpCUl/48Ltt1r9nShjYD+GhyJhARhLFn98771dFkVSp6W068V5FMLqBM4CABDEjaNUBoLcR1gKWxwTIfjYFxt3U=
  on:
    tags: true
    repo: nfantone/mu-koan-router
    node_js: '7'
